### ISSUE TITLE
Data analytics

### ISSUE THREAD

**Issue by TheOneHoff** [UWA-CITS3200-18-2021/ReSQ#51]
Setup some basic data analytics for most requested info such as peak times, units with the most enquiries, etc.

**Comment by frinzekt** [comment]
More information for this issue is needed, and the possibility of splitting this to more separate issues

**Comment by frinzekt** [comment]
Do we need this feature? As per #47, if we are doing this feature, then it only makes sense to do data analytics on the exported attributes.

In some extent, this becomes a nice-2-haves now, because excel will be a more powerful tool for analytics on the exported data, rather than us implementing the feature in the web application itself

**Comment by TheOneHoff** [comment]
I agree. Now that the client has specified he would like to export the data, we should focus on increasing functionality for that, rather then implementing simplistic analytics ourselves

**Comment by Alexkszzz** [comment]
The recent response from the client stated that it's good to have a week-to-week analysis. Two main requests from the client are:
 -  Having day comparisons (the number of sessions on different weekdays)
 -  Amount of sessions for different units during the week (to identify emerging units). For this one, maybe we generate the top 5 units, then the rest will be put in a column called 'Others'?

**Comment by TheOneHoff** [comment]
Baseline implementation finished in #77
